### ISSUE TITLE
[QUESTION] or [BUG] model in separate library

### ISSUE THREAD

**Issue by konne** [TypedProject/tsed#1205] opened 2021-01-22 13:34 UTC
Hi,

I have a strange issue. I placed all the models into a separate library because this is defining all the exchanged classes
The separate lib is compiled with typescript and I find all decorators as well in the file.

Now the issue. The response is fully correct in the open API spec, but if I use Models.ParameterRequest instead of ModelsParameterRequest in the BodyParam the generated open API spec is just an empty object {}

What I don't understand is why this extremely simple reExport of the class solves the issue?

```js
import * as Models from "@easybsb/bsbjs/models"

export class ModelsParameterRequest extends Models.ParameterRequest {

} 
...

  @Post("/JQ")
  @Returns(200, Models.ValueResponse).ContentType("application/json")
  async fetchValues(
    @BodyParams()
    @Description('The body contains an array of just one simple ParameterRequest object')
    @Example([{ parameter: 700 }, { parameter: 710 }])
    @Required()
    @OneOf(from(ModelsParameterRequest), array().items(from(ModelsParameterRequest)))
    payloadArrayOrItem: ParameterRequest | ParameterRequest[]): Promise<ValueResponse> {

    return this.bsb.fetchValues(payloadArrayOrItem)
  }
```

thx Konrad

**Comment by Romakita** [comment] 2021-01-22 13:51
The problem is probably related to the dependencies resolution. If your @easybsb/bsbjs/models add @tsed/schema as dependencies with a different version from your project, the metadata won't be collected as expected. 

The fix: set @tsed/schema as peerDependencies (and devDependencies).

See you
Romain

**Comment by konne** [comment] 2021-01-22 14:29
Hi Romain,

As a side note, this also brings me into trouble if both js libs always need the same @tsed/schema version.
Is there any possibility to get around this side problem? For example, in angular you can easily build components with decorators that add extra metadata and you don't need the exact same Version.

Thx for the hints, but it doesn't help (I updated both with the exact same version 6.22.2)

and this does not explain for me the behavior, because:
1.  this extreme simple export ... extends ...  -> helps
2. the @Returns works perfectly

bye
Konrad

**Comment by Romakita** [comment] 2021-01-22 14:32
yes because Angular run his code in the same browser context, where the Nodejs create a context per modules.

Can you share me your package.json for the module and the project please :)

**Comment by Romakita** [comment] 2021-01-22 14:33
> and this does not explain for me the behavior, because:
> this extreme simple export ... extends ... -> helps
> the @returns works perfectly
Maybe a reproducible repo example could help to analyse the problem.

**Comment by konne** [comment] 2021-01-22 14:41
I will create a simple testcase

**Comment by konne** [comment] 2021-01-22 16:10
Hi,

https://github.com/konne/tsed-issue

please checkout and make an npm i and npm run start in the server
I just try to load it form the /lib
It is working if I don't define an oneOf(..) Post P2 but not with this.

**Comment by Romakita** [comment] 2021-01-22 17:06
Hi,

This is exactly that I was expected :)

Just fix your package.json (`@easybsb/bsbjs`):

```jsonc
{
  "name": "@easybsb/bsbjs",
  "version": "1.0.0",
  "description": "",
  "main": "dist/index.js",
   "types": "dist/index.d.ts",
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@tsed/schema": "^6.22.2"
    "@types/json-schema": "^7.0.7", 
    "typescript": "^4.1.3"
  },
  "peerDependencies": {
      "@tsed/schema": "^6.22.2"
   }
}
```

Then publish you package on Npm and reinstall the package `@easybsb/bsbjs` and additionally run `npm dedup` :) 

it should solve your issue!
Romain

**Comment by Romakita** [comment] 2021-03-02 07:05
@konne Can I close this issue?

**Closed** 2021-03-12 09:55 UTC
Labels: question
