### ISSUE TITLE
[QUESTION] GraphQL + Passport

### ISSUE THREAD

**Issue by CoryBall** [TypedProject/tsed#1255] opened 2021-02-24 23:56 UTC
While there are separate guides for these, how do they work together using Ts.ED conventions? I've tried using [graphql-passport](https://github.com/jkettmann/graphql-passport) and modifying the code from the Ts.ED documentation, but I cannot figure out how to get anything to work correctly. While an answer or guidance would be greatly appreciated, I think it is a common problem developers face when developing a GraphQL server. Maybe an example repo, or a small article in the docs to an acceptable solution? I'm loving the framework, and once I get this problem solved I'm excited to dig into it more.

**Comment by CoryBall** [comment] 2021-02-25 23:52
And also related: Middleware with GraphQL. Middleware made from the documentation works with Controllers, but not with Graphql (e.i. getting a bearer token from headers and putting it in req.user for the GraphQL Resolver context parameter)

**Comment by Romakita** [comment] 2021-02-26 00:10
Hello @CoryBall 
Sorry for my lating answer. I don’t use graphql , So my knowledge is very basic. 
To start investigation on middleware issue and solve it quickly, a repo example with the minimal code and your expectation (comments in code it’s fine) will help me a lot. 

For graph-passport... I don’t know how to do that. I need a repo with a grapql example to understand the mechanism and provide you a basic example.

see you :)

**Comment by Romakita** [comment] 2021-02-26 00:14
Ok the example of passport graphql is understable, I try to give you an example tomorrow.

**Comment by Romakita** [comment] 2021-02-26 09:49
Ok the PR is ready :)
You can take a look on the PR to see a working example with graphql-passport: https://github.com/TypedProject/tsed/pull/1256

See you
Romain

**Comment by CoryBall** [comment] 2021-02-26 19:58
Awesome! That looks great, I'll play with it. Do you still want a repo with a graphql + middleware example? I wasn't able to get that yesterday but I believe I can get that to you today. (CST)

**Comment by Romakita** [comment] 2021-02-26 20:24
I think the issue is fixed with the latest release. Passport is also a middleware which must be executed before graphql.

**Comment by Romakita** [comment] 2021-02-26 20:28
I just need your feedback before closing the issue ;)

**Comment by CoryBall** [comment] 2021-02-26 20:58
Everything works great! I appreciate the quick replies and fix. Both passport and middleware is working as expected with 6.24.4

**Closed** 2021-03-02 01:41 UTC
Labels: question

**Comment by Romakita** [comment] 2021-03-02 07:01
Great :)

Please consider [supporting](https://tsed.io/support.html) the framework if it provides value to you or your company and this support was of help to you. Supporting the framework means, amongst other things, that such support will be available in the future.
